// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDMqD9HTssyxM8U2EXQ5zu6dNGnrQhAg',
    appId: '1:526297323248:web:c00f4de087eb4e8d419435',
    messagingSenderId: '526297323248',
    projectId: 'finance-management-firebase',
    authDomain: 'finance-management-firebase.firebaseapp.com',
    storageBucket: 'finance-management-firebase.firebasestorage.app',
    measurementId: 'G-G6LT9XM0V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnG79ZnQaTsmf1Chr2RxVe6n-S0bg0nQ',
    appId: '1:526297323248:android:c0586c4009530132419435',
    messagingSenderId: '526297323248',
    projectId: 'finance-management-firebase',
    storageBucket: 'finance-management-firebase.firebasestorage.app',
  );
}
